// Code generated by cmd/cgo -godefs from defs_qnx.go and converted to
// the runtime's naming by hand; see defs_qnx.go for the command. Run it
// with GOARCH=arm and a C compiler for ARM QNX 6.5, and with Regs set to
// C.ARM_CPU_REGISTERS.

package runtime

import "unsafe"

const (
	_EINTR     = 0x4
	_EFAULT    = 0xe
	_EAGAIN    = 0xb
	_ENOSYS    = 0x59
	_ETIMEDOUT = 0x104

	_O_RDONLY   = 0x0
	_O_WRONLY   = 0x1
	_O_NONBLOCK = 0x80
	_O_CREAT    = 0x100
	_O_TRUNC    = 0x200
	_O_CLOEXEC  = 0x2000

	_F_GETFL = 0x3
	_F_SETFL = 0x4
	_F_GETFD = 0x1

	_PROT_NONE  = 0x0
	_PROT_READ  = 0x100
	_PROT_WRITE = 0x200
	_PROT_EXEC  = 0x400

	_MAP_ANON    = 0x80000
	_MAP_PRIVATE = 0x2
	_MAP_FIXED   = 0x10
	_MAP_NOINIT  = 0x4000

	_POSIX_MADV_DONTNEED = 0x4

	_SA_SIGINFO   = 0x2
	_SA_RESETHAND = 0x4

	_SIG_BLOCK   = 0x0
	_SIG_UNBLOCK = 0x1
	_SIG_SETMASK = 0x2

	_PTHREAD_CREATE_DETACHED = 0x1

	_SIGHUP    = 0x1
	_SIGINT    = 0x2
	_SIGQUIT   = 0x3
	_SIGILL    = 0x4
	_SIGTRAP   = 0x5
	_SIGABRT   = 0x6
	_SIGEMT    = 0x7
	_SIGFPE    = 0x8
	_SIGKILL   = 0x9
	_SIGBUS    = 0xa
	_SIGSEGV   = 0xb
	_SIGSYS    = 0xc
	_SIGPIPE   = 0xd
	_SIGALRM   = 0xe
	_SIGTERM   = 0xf
	_SIGUSR1   = 0x10
	_SIGUSR2   = 0x11
	_SIGCHLD   = 0x12
	_SIGPWR    = 0x13
	_SIGWINCH  = 0x14
	_SIGURG    = 0x15
	_SIGPOLL   = 0x16
	_SIGSTOP   = 0x17
	_SIGTSTP   = 0x18
	_SIGCONT   = 0x19
	_SIGTTIN   = 0x1a
	_SIGTTOU   = 0x1b
	_SIGVTALRM = 0x1c
	_SIGPROF   = 0x1d
	_SIGXCPU   = 0x1e
	_SIGXFSZ   = 0x1f
	_SIGRTMIN  = 0x29
	_SIGRTMAX  = 0x38
	_NSIG      = 0x39

	_FPE_INTDIV = 0x1
	_FPE_INTOVF = 0x2
	_FPE_FLTDIV = 0x3
	_FPE_FLTOVF = 0x4
	_FPE_FLTUND = 0x5
	_FPE_FLTRES = 0x6
	_FPE_FLTINV = 0x7
	_FPE_FLTSUB = 0x8

	_BUS_ADRALN = 0x1
	_BUS_ADRERR = 0x2
	_BUS_OBJERR = 0x3

	_SEGV_MAPERR = 0x1
	_SEGV_ACCERR = 0x2

	_SI_USER = 0x0

	_ITIMER_REAL    = 0x0
	_ITIMER_VIRTUAL = 0x1
	_ITIMER_PROF    = 0x2

	_CLOCK_REALTIME  = 0x0
	_CLOCK_MONOTONIC = 0x2

	_SC_NPROCESSORS_ONLN = 0x5b
	_SC_PAGESIZE         = 0xb
)

type sigset struct {
	__bits [2]uint32
}

type siginfo struct {
	si_signo int32
	si_code  int32
	si_errno int32
	// The fault member of the __data union: __fltno, __fltip,
	// __addr, __bdslot, then padding to the union's 28 bytes.
	si_fltno  int32
	si_fltip  uintptr
	si_addr   uintptr
	si_bdslot int32
	_         [12]byte
}

type sigactiont struct {
	sa_handler uintptr
	sa_flags   int32
	sa_mask    sigset
}

type stackt struct {
	ss_sp    uintptr
	ss_size  uintptr
	ss_flags int32
}

// time_t is an unsigned 32-bit integer on QNX 6.5.
type timespec struct {
	tv_sec  uint32
	tv_nsec int32
}

//go:nosplit
func (ts *timespec) setNsec(ns int64) {
	ts.tv_sec = uint32(ns / 1e9)
	ts.tv_nsec = int32(ns % 1e9)
}

type timeval struct {
	tv_sec  uint32
	tv_usec int32
}

func (tv *timeval) set_usec(x int32) {
	tv.tv_usec = x
}

type itimerval struct {
	it_interval timeval
	it_value    timeval
}

// ARM_CPU_REGISTERS: the 16 general registers r0..r15 (r13 is sp, r14
// is lr, r15 is pc) and spsr (the saved program status register, which
// Go reads as cpsr).
type regsarm struct {
	gpr  [16]uint32
	spsr uint32
}

// mcontext_t is { ARM_CPU_REGISTERS cpu; ARM_FPU_REGISTERS fpu }. The
// fpu member holds the VFP state (32 doublewords, then fpscr, fpexc and
// two implementation registers) and is 8-byte aligned, so four bytes of
// padding follow cpu. The runtime reads only cpu; fpu is opaque here.
type mcontext struct {
	cpu regsarm
	_   [4]byte
	fpu [272]byte
}

type ucontext struct {
	uc_link     *ucontext
	uc_sigmask  sigset
	uc_stack    stackt
	uc_mcontext mcontext
}

// pthread_t is the thread ID.
type pthread int32

type pthreadattr struct {
	_ [76]byte
}

type semt struct {
	_ [8]byte
}

// Sizes and offsets measured with the QNX 6.5 ARM headers. Each pair of
// array types has a negative length, and so fails to compile, unless
// the Go layout matches.
var (
	_ [unsafe.Sizeof(sigset{}) - 8]byte
	_ [8 - unsafe.Sizeof(sigset{})]byte
	_ [unsafe.Sizeof(siginfo{}) - 40]byte
	_ [40 - unsafe.Sizeof(siginfo{})]byte
	_ [unsafe.Sizeof(sigactiont{}) - 16]byte
	_ [16 - unsafe.Sizeof(sigactiont{})]byte
	_ [unsafe.Sizeof(mcontext{}) - 344]byte
	_ [344 - unsafe.Sizeof(mcontext{})]byte
	_ [unsafe.Sizeof(ucontext{}) - 368]byte
	_ [368 - unsafe.Sizeof(ucontext{})]byte
	_ [unsafe.Offsetof(ucontext{}.uc_mcontext) - 24]byte
	_ [24 - unsafe.Offsetof(ucontext{}.uc_mcontext)]byte
	_ [unsafe.Offsetof(siginfo{}.si_addr) - 20]byte
	_ [20 - unsafe.Offsetof(siginfo{}.si_addr)]byte
)
