// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package runtime

// QNX numbers its signals like System V. Signals 32 through 40 are
// reserved, 41 through 56 are the real-time signals, and 57 and up
// (SIGSELECT, SIGPHOTON) are always masked and belong to libc.
var sigtable = [...]sigTabT{
	/*  0 */ {0, "SIGNONE: no trap"},
	/*  1 */ {_SigNotify + _SigKill, "SIGHUP: terminal line hangup"},
	/*  2 */ {_SigNotify + _SigKill, "SIGINT: interrupt"},
	/*  3 */ {_SigNotify + _SigThrow, "SIGQUIT: quit"},
	/*  4 */ {_SigThrow + _SigUnblock, "SIGILL: illegal instruction"},
	/*  5 */ {_SigThrow + _SigUnblock, "SIGTRAP: trace trap"},
	/*  6 */ {_SigNotify + _SigThrow, "SIGABRT: abort"},
	/*  7 */ {_SigThrow, "SIGEMT: emulate instruction executed"},
	/*  8 */ {_SigPanic + _SigUnblock, "SIGFPE: floating-point exception"},
	/*  9 */ {0, "SIGKILL: kill"},
	/* 10 */ {_SigPanic + _SigUnblock, "SIGBUS: bus error"},
	/* 11 */ {_SigPanic + _SigUnblock, "SIGSEGV: segmentation violation"},
	/* 12 */ {_SigThrow, "SIGSYS: bad system call"},
	/* 13 */ {_SigNotify, "SIGPIPE: write to broken pipe"},
	/* 14 */ {_SigNotify, "SIGALRM: alarm clock"},
	/* 15 */ {_SigNotify + _SigKill, "SIGTERM: termination"},
	/* 16 */ {_SigNotify, "SIGUSR1: user-defined signal 1"},
	/* 17 */ {_SigNotify, "SIGUSR2: user-defined signal 2"},
	/* 18 */ {_SigNotify + _SigUnblock + _SigIgn, "SIGCHLD: child status has changed"},
	/* 19 */ {_SigNotify, "SIGPWR: power failure restart"},
	/* 20 */ {_SigNotify + _SigIgn, "SIGWINCH: window size change"},
	/* 21 */ {_SigNotify + _SigIgn, "SIGURG: urgent condition on socket"},
	/* 22 */ {_SigNotify, "SIGPOLL: pollable event occurred"},
	/* 23 */ {0, "SIGSTOP: stop"},
	/* 24 */ {_SigNotify + _SigDefault + _SigIgn, "SIGTSTP: keyboard stop"},
	/* 25 */ {_SigNotify + _SigDefault + _SigIgn, "SIGCONT: continue after stop"},
	/* 26 */ {_SigNotify + _SigDefault + _SigIgn, "SIGTTIN: background read from tty"},
	/* 27 */ {_SigNotify + _SigDefault + _SigIgn, "SIGTTOU: background write to tty"},
	/* 28 */ {_SigNotify, "SIGVTALRM: virtual alarm clock"},
	/* 29 */ {_SigNotify + _SigUnblock, "SIGPROF: profiling alarm clock"},
	/* 30 */ {_SigNotify, "SIGXCPU: cpu limit exceeded"},
	/* 31 */ {_SigNotify, "SIGXFSZ: file size limit exceeded"},
	/* 32 */ {0, "signal 32: reserved"},
	/* 33 */ {0, "signal 33: reserved"},
	/* 34 */ {0, "signal 34: reserved"},
	/* 35 */ {0, "signal 35: reserved"},
	/* 36 */ {0, "signal 36: reserved"},
	/* 37 */ {0, "signal 37: reserved"},
	/* 38 */ {0, "signal 38: reserved"},
	/* 39 */ {0, "signal 39: reserved"},
	/* 40 */ {0, "signal 40: reserved"},
	/* 41 */ {_SigNotify, "signal 41"},
	/* 42 */ {_SigNotify, "signal 42"},
	/* 43 */ {_SigNotify, "signal 43"},
	/* 44 */ {_SigNotify, "signal 44"},
	/* 45 */ {_SigNotify, "signal 45"},
	/* 46 */ {_SigNotify, "signal 46"},
	/* 47 */ {_SigNotify, "signal 47"},
	/* 48 */ {_SigNotify, "signal 48"},
	/* 49 */ {_SigNotify, "signal 49"},
	/* 50 */ {_SigNotify, "signal 50"},
	/* 51 */ {_SigNotify, "signal 51"},
	/* 52 */ {_SigNotify, "signal 52"},
	/* 53 */ {_SigNotify, "signal 53"},
	/* 54 */ {_SigNotify, "signal 54"},
	/* 55 */ {_SigNotify, "signal 55"},
	/* 56 */ {_SigNotify, "signal 56"},
}
