// Code generated by mkasserts_qnx.go; DO NOT EDIT.

// Compile-time checks that the struct layouts in ztypes_qnx_386.go match the C
// headers. Any C compiler for the target must accept this file:
//	$CC -fsigned-char -D_FILE_OFFSET_BITS=64 -D_QNX_SOURCE -fsyntax-only zasserts_qnx_386.h

#include <stddef.h>
// mkall.sh passes -D_FILE_OFFSET_BITS=64 -D_QNX_SOURCE on the command line:
// cgo's prolog includes <stddef.h> before this preamble, and the QNX headers
// fix the width of off_t, ino_t and blkcnt_t on first inclusion, so a #define
// here would come too late.
#include <dirent.h>
#include <fcntl.h>
#include <limits.h>
#include <signal.h>
#include <spawn.h>
#include <termios.h>
#include <stdio.h>
#include <unistd.h>
#include <sys/mman.h>
#include <sys/param.h>
#include <sys/resource.h>
#include <sys/select.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/un.h>
#include <sys/utsname.h>
#include <sys/wait.h>
#include <net/if.h>
#include <net/if_dl.h>
#include <net/route.h>
#include <netinet/in.h>
#include <netinet/icmp6.h>
#include <netinet/tcp.h>

enum {
	sizeofPtr = sizeof(void*),
};

union sockaddr_all {
	struct sockaddr s1;	// this one gets used for fields
	struct sockaddr_in s2;	// these pad it out
	struct sockaddr_in6 s3;
	struct sockaddr_un s4;
	struct sockaddr_dl s5;
};

struct sockaddr_any {
	struct sockaddr addr;
	char pad[sizeof(union sockaddr_all) - sizeof(struct sockaddr)];
};

typedef char chk_1[(sizeof(struct sched_param) == 40) ? 1 : -1]; /* _Sched_param */
typedef char chk_2[(offsetof(struct sched_param, sched_priority) == 0) ? 1 : -1]; /* _Sched_param.Priority */
typedef char chk_3[(sizeof(((struct sched_param *)0)->sched_priority) == 4) ? 1 : -1]; /* _Sched_param.Priority */
typedef char chk_4[(offsetof(struct sched_param, sched_curpriority) == 4) ? 1 : -1]; /* _Sched_param.Curpriority */
typedef char chk_5[(sizeof(((struct sched_param *)0)->sched_curpriority) == 4) ? 1 : -1]; /* _Sched_param.Curpriority */
typedef char chk_6[(offsetof(struct sched_param, __ss_un) == 8) ? 1 : -1]; /* _Sched_param.X__ss_un */
typedef char chk_7[(sizeof(((struct sched_param *)0)->__ss_un) == 32) ? 1 : -1]; /* _Sched_param.X__ss_un */
typedef char chk_8[(sizeof(struct inheritance) == 88) ? 1 : -1]; /* _Inheritance */
typedef char chk_9[(offsetof(struct inheritance, flags) == 0) ? 1 : -1]; /* _Inheritance.Flags */
typedef char chk_10[(sizeof(((struct inheritance *)0)->flags) == 4) ? 1 : -1]; /* _Inheritance.Flags */
typedef char chk_11[(offsetof(struct inheritance, pgroup) == 4) ? 1 : -1]; /* _Inheritance.Pgroup */
typedef char chk_12[(sizeof(((struct inheritance *)0)->pgroup) == 4) ? 1 : -1]; /* _Inheritance.Pgroup */
typedef char chk_13[(offsetof(struct inheritance, sigmask) == 8) ? 1 : -1]; /* _Inheritance.Sigmask */
typedef char chk_14[(sizeof(((struct inheritance *)0)->sigmask) == 8) ? 1 : -1]; /* _Inheritance.Sigmask */
typedef char chk_15[(offsetof(struct inheritance, sigdefault) == 16) ? 1 : -1]; /* _Inheritance.Sigdefault */
typedef char chk_16[(sizeof(((struct inheritance *)0)->sigdefault) == 8) ? 1 : -1]; /* _Inheritance.Sigdefault */
typedef char chk_17[(offsetof(struct inheritance, sigignore) == 24) ? 1 : -1]; /* _Inheritance.Sigignore */
typedef char chk_18[(sizeof(((struct inheritance *)0)->sigignore) == 8) ? 1 : -1]; /* _Inheritance.Sigignore */
typedef char chk_19[(offsetof(struct inheritance, stack_max) == 32) ? 1 : -1]; /* _Inheritance.Max */
typedef char chk_20[(sizeof(((struct inheritance *)0)->stack_max) == 4) ? 1 : -1]; /* _Inheritance.Max */
typedef char chk_21[(offsetof(struct inheritance, policy) == 36) ? 1 : -1]; /* _Inheritance.Policy */
typedef char chk_22[(sizeof(((struct inheritance *)0)->policy) == 4) ? 1 : -1]; /* _Inheritance.Policy */
typedef char chk_23[(offsetof(struct inheritance, nd) == 40) ? 1 : -1]; /* _Inheritance.Nd */
typedef char chk_24[(sizeof(((struct inheritance *)0)->nd) == 4) ? 1 : -1]; /* _Inheritance.Nd */
typedef char chk_25[(offsetof(struct inheritance, runmask) == 44) ? 1 : -1]; /* _Inheritance.Runmask */
typedef char chk_26[(sizeof(((struct inheritance *)0)->runmask) == 4) ? 1 : -1]; /* _Inheritance.Runmask */
typedef char chk_27[(offsetof(struct inheritance, param) == 48) ? 1 : -1]; /* _Inheritance.Param */
typedef char chk_28[(sizeof(((struct inheritance *)0)->param) == 40) ? 1 : -1]; /* _Inheritance.Param */
typedef char chk_29[(sizeof(short) == 2) ? 1 : -1]; /* _C_short */
typedef char chk_30[(sizeof(int) == 4) ? 1 : -1]; /* _C_int */
typedef char chk_31[(sizeof(long) == 4) ? 1 : -1]; /* _C_long */
typedef char chk_32[(sizeof(long long) == 8) ? 1 : -1]; /* _C_long_long */
typedef char chk_33[(sizeof(struct timespec) == 8) ? 1 : -1]; /* Timespec */
typedef char chk_34[(offsetof(struct timespec, tv_sec) == 0) ? 1 : -1]; /* Timespec.Sec */
typedef char chk_35[(sizeof(((struct timespec *)0)->tv_sec) == 4) ? 1 : -1]; /* Timespec.Sec */
typedef char chk_36[(offsetof(struct timespec, tv_nsec) == 4) ? 1 : -1]; /* Timespec.Nsec */
typedef char chk_37[(sizeof(((struct timespec *)0)->tv_nsec) == 4) ? 1 : -1]; /* Timespec.Nsec */
typedef char chk_38[(sizeof(struct timeval) == 8) ? 1 : -1]; /* Timeval */
typedef char chk_39[(offsetof(struct timeval, tv_sec) == 0) ? 1 : -1]; /* Timeval.Sec */
typedef char chk_40[(sizeof(((struct timeval *)0)->tv_sec) == 4) ? 1 : -1]; /* Timeval.Sec */
typedef char chk_41[(offsetof(struct timeval, tv_usec) == 4) ? 1 : -1]; /* Timeval.Usec */
typedef char chk_42[(sizeof(((struct timeval *)0)->tv_usec) == 4) ? 1 : -1]; /* Timeval.Usec */
typedef char chk_43[(sizeof(struct rusage) == 72) ? 1 : -1]; /* Rusage */
typedef char chk_44[(offsetof(struct rusage, ru_utime) == 0) ? 1 : -1]; /* Rusage.Utime */
typedef char chk_45[(sizeof(((struct rusage *)0)->ru_utime) == 8) ? 1 : -1]; /* Rusage.Utime */
typedef char chk_46[(offsetof(struct rusage, ru_stime) == 8) ? 1 : -1]; /* Rusage.Stime */
typedef char chk_47[(sizeof(((struct rusage *)0)->ru_stime) == 8) ? 1 : -1]; /* Rusage.Stime */
typedef char chk_48[(offsetof(struct rusage, ru_maxrss) == 16) ? 1 : -1]; /* Rusage.Maxrss */
typedef char chk_49[(sizeof(((struct rusage *)0)->ru_maxrss) == 4) ? 1 : -1]; /* Rusage.Maxrss */
typedef char chk_50[(offsetof(struct rusage, ru_ixrss) == 20) ? 1 : -1]; /* Rusage.Ixrss */
typedef char chk_51[(sizeof(((struct rusage *)0)->ru_ixrss) == 4) ? 1 : -1]; /* Rusage.Ixrss */
typedef char chk_52[(offsetof(struct rusage, ru_idrss) == 24) ? 1 : -1]; /* Rusage.Idrss */
typedef char chk_53[(sizeof(((struct rusage *)0)->ru_idrss) == 4) ? 1 : -1]; /* Rusage.Idrss */
typedef char chk_54[(offsetof(struct rusage, ru_isrss) == 28) ? 1 : -1]; /* Rusage.Isrss */
typedef char chk_55[(sizeof(((struct rusage *)0)->ru_isrss) == 4) ? 1 : -1]; /* Rusage.Isrss */
typedef char chk_56[(offsetof(struct rusage, ru_minflt) == 32) ? 1 : -1]; /* Rusage.Minflt */
typedef char chk_57[(sizeof(((struct rusage *)0)->ru_minflt) == 4) ? 1 : -1]; /* Rusage.Minflt */
typedef char chk_58[(offsetof(struct rusage, ru_majflt) == 36) ? 1 : -1]; /* Rusage.Majflt */
typedef char chk_59[(sizeof(((struct rusage *)0)->ru_majflt) == 4) ? 1 : -1]; /* Rusage.Majflt */
typedef char chk_60[(offsetof(struct rusage, ru_nswap) == 40) ? 1 : -1]; /* Rusage.Nswap */
typedef char chk_61[(sizeof(((struct rusage *)0)->ru_nswap) == 4) ? 1 : -1]; /* Rusage.Nswap */
typedef char chk_62[(offsetof(struct rusage, ru_inblock) == 44) ? 1 : -1]; /* Rusage.Inblock */
typedef char chk_63[(sizeof(((struct rusage *)0)->ru_inblock) == 4) ? 1 : -1]; /* Rusage.Inblock */
typedef char chk_64[(offsetof(struct rusage, ru_oublock) == 48) ? 1 : -1]; /* Rusage.Oublock */
typedef char chk_65[(sizeof(((struct rusage *)0)->ru_oublock) == 4) ? 1 : -1]; /* Rusage.Oublock */
typedef char chk_66[(offsetof(struct rusage, ru_msgsnd) == 52) ? 1 : -1]; /* Rusage.Msgsnd */
typedef char chk_67[(sizeof(((struct rusage *)0)->ru_msgsnd) == 4) ? 1 : -1]; /* Rusage.Msgsnd */
typedef char chk_68[(offsetof(struct rusage, ru_msgrcv) == 56) ? 1 : -1]; /* Rusage.Msgrcv */
typedef char chk_69[(sizeof(((struct rusage *)0)->ru_msgrcv) == 4) ? 1 : -1]; /* Rusage.Msgrcv */
typedef char chk_70[(offsetof(struct rusage, ru_nsignals) == 60) ? 1 : -1]; /* Rusage.Nsignals */
typedef char chk_71[(sizeof(((struct rusage *)0)->ru_nsignals) == 4) ? 1 : -1]; /* Rusage.Nsignals */
typedef char chk_72[(offsetof(struct rusage, ru_nvcsw) == 64) ? 1 : -1]; /* Rusage.Nvcsw */
typedef char chk_73[(sizeof(((struct rusage *)0)->ru_nvcsw) == 4) ? 1 : -1]; /* Rusage.Nvcsw */
typedef char chk_74[(offsetof(struct rusage, ru_nivcsw) == 68) ? 1 : -1]; /* Rusage.Nivcsw */
typedef char chk_75[(sizeof(((struct rusage *)0)->ru_nivcsw) == 4) ? 1 : -1]; /* Rusage.Nivcsw */
typedef char chk_76[(sizeof(struct rlimit) == 16) ? 1 : -1]; /* Rlimit */
typedef char chk_77[(offsetof(struct rlimit, rlim_cur) == 0) ? 1 : -1]; /* Rlimit.Cur */
typedef char chk_78[(sizeof(((struct rlimit *)0)->rlim_cur) == 8) ? 1 : -1]; /* Rlimit.Cur */
typedef char chk_79[(offsetof(struct rlimit, rlim_max) == 8) ? 1 : -1]; /* Rlimit.Max */
typedef char chk_80[(sizeof(((struct rlimit *)0)->rlim_max) == 8) ? 1 : -1]; /* Rlimit.Max */
typedef char chk_81[(sizeof(pid_t) == 4) ? 1 : -1]; /* _Pid_t */
typedef char chk_82[(sizeof(gid_t) == 4) ? 1 : -1]; /* _Gid_t */
typedef char chk_83[(sizeof(struct stat) == 72) ? 1 : -1]; /* Stat_t */
typedef char chk_84[(offsetof(struct stat, st_ino) == 0) ? 1 : -1]; /* Stat_t.Ino */
typedef char chk_85[(sizeof(((struct stat *)0)->st_ino) == 8) ? 1 : -1]; /* Stat_t.Ino */
typedef char chk_86[(offsetof(struct stat, st_size) == 8) ? 1 : -1]; /* Stat_t.Size */
typedef char chk_87[(sizeof(((struct stat *)0)->st_size) == 8) ? 1 : -1]; /* Stat_t.Size */
typedef char chk_88[(offsetof(struct stat, st_dev) == 16) ? 1 : -1]; /* Stat_t.Dev */
typedef char chk_89[(sizeof(((struct stat *)0)->st_dev) == 4) ? 1 : -1]; /* Stat_t.Dev */
typedef char chk_90[(offsetof(struct stat, st_rdev) == 20) ? 1 : -1]; /* Stat_t.Rdev */
typedef char chk_91[(sizeof(((struct stat *)0)->st_rdev) == 4) ? 1 : -1]; /* Stat_t.Rdev */
typedef char chk_92[(offsetof(struct stat, st_uid) == 24) ? 1 : -1]; /* Stat_t.Uid */
typedef char chk_93[(sizeof(((struct stat *)0)->st_uid) == 4) ? 1 : -1]; /* Stat_t.Uid */
typedef char chk_94[(offsetof(struct stat, st_gid) == 28) ? 1 : -1]; /* Stat_t.Gid */
typedef char chk_95[(sizeof(((struct stat *)0)->st_gid) == 4) ? 1 : -1]; /* Stat_t.Gid */
typedef char chk_96[(offsetof(struct stat, st_mtime) == 32) ? 1 : -1]; /* Stat_t.Mtime */
typedef char chk_97[(sizeof(((struct stat *)0)->st_mtime) == 4) ? 1 : -1]; /* Stat_t.Mtime */
typedef char chk_98[(offsetof(struct stat, st_atime) == 36) ? 1 : -1]; /* Stat_t.Atime */
typedef char chk_99[(sizeof(((struct stat *)0)->st_atime) == 4) ? 1 : -1]; /* Stat_t.Atime */
typedef char chk_100[(offsetof(struct stat, st_ctime) == 40) ? 1 : -1]; /* Stat_t.Ctime */
typedef char chk_101[(sizeof(((struct stat *)0)->st_ctime) == 4) ? 1 : -1]; /* Stat_t.Ctime */
typedef char chk_102[(offsetof(struct stat, st_mode) == 44) ? 1 : -1]; /* Stat_t.Mode */
typedef char chk_103[(sizeof(((struct stat *)0)->st_mode) == 4) ? 1 : -1]; /* Stat_t.Mode */
typedef char chk_104[(offsetof(struct stat, st_nlink) == 48) ? 1 : -1]; /* Stat_t.Nlink */
typedef char chk_105[(sizeof(((struct stat *)0)->st_nlink) == 4) ? 1 : -1]; /* Stat_t.Nlink */
typedef char chk_106[(offsetof(struct stat, st_blocksize) == 52) ? 1 : -1]; /* Stat_t.Blocksize */
typedef char chk_107[(sizeof(((struct stat *)0)->st_blocksize) == 4) ? 1 : -1]; /* Stat_t.Blocksize */
typedef char chk_108[(offsetof(struct stat, st_nblocks) == 56) ? 1 : -1]; /* Stat_t.Nblocks */
typedef char chk_109[(sizeof(((struct stat *)0)->st_nblocks) == 4) ? 1 : -1]; /* Stat_t.Nblocks */
typedef char chk_110[(offsetof(struct stat, st_blksize) == 60) ? 1 : -1]; /* Stat_t.Blksize */
typedef char chk_111[(sizeof(((struct stat *)0)->st_blksize) == 4) ? 1 : -1]; /* Stat_t.Blksize */
typedef char chk_112[(offsetof(struct stat, st_blocks) == 64) ? 1 : -1]; /* Stat_t.Blocks */
typedef char chk_113[(sizeof(((struct stat *)0)->st_blocks) == 8) ? 1 : -1]; /* Stat_t.Blocks */
typedef char chk_114[(sizeof(struct flock) == 32) ? 1 : -1]; /* Flock_t */
typedef char chk_115[(offsetof(struct flock, l_type) == 0) ? 1 : -1]; /* Flock_t.Type */
typedef char chk_116[(sizeof(((struct flock *)0)->l_type) == 2) ? 1 : -1]; /* Flock_t.Type */
typedef char chk_117[(offsetof(struct flock, l_whence) == 2) ? 1 : -1]; /* Flock_t.Whence */
typedef char chk_118[(sizeof(((struct flock *)0)->l_whence) == 2) ? 1 : -1]; /* Flock_t.Whence */
typedef char chk_119[(offsetof(struct flock, l_zero1) == 4) ? 1 : -1]; /* Flock_t.Zero1 */
typedef char chk_120[(sizeof(((struct flock *)0)->l_zero1) == 4) ? 1 : -1]; /* Flock_t.Zero1 */
typedef char chk_121[(offsetof(struct flock, l_start) == 8) ? 1 : -1]; /* Flock_t.Start */
typedef char chk_122[(sizeof(((struct flock *)0)->l_start) == 8) ? 1 : -1]; /* Flock_t.Start */
typedef char chk_123[(offsetof(struct flock, l_len) == 16) ? 1 : -1]; /* Flock_t.Len */
typedef char chk_124[(sizeof(((struct flock *)0)->l_len) == 8) ? 1 : -1]; /* Flock_t.Len */
typedef char chk_125[(offsetof(struct flock, l_pid) == 24) ? 1 : -1]; /* Flock_t.Pid */
typedef char chk_126[(sizeof(((struct flock *)0)->l_pid) == 4) ? 1 : -1]; /* Flock_t.Pid */
typedef char chk_127[(offsetof(struct flock, l_sysid) == 28) ? 1 : -1]; /* Flock_t.Sysid */
typedef char chk_128[(sizeof(((struct flock *)0)->l_sysid) == 4) ? 1 : -1]; /* Flock_t.Sysid */
typedef char chk_129[(sizeof(struct dirent) == 24) ? 1 : -1]; /* Dirent */
typedef char chk_130[(offsetof(struct dirent, d_ino) == 0) ? 1 : -1]; /* Dirent.Ino */
typedef char chk_131[(sizeof(((struct dirent *)0)->d_ino) == 8) ? 1 : -1]; /* Dirent.Ino */
typedef char chk_132[(offsetof(struct dirent, d_offset) == 8) ? 1 : -1]; /* Dirent.Offset */
typedef char chk_133[(sizeof(((struct dirent *)0)->d_offset) == 8) ? 1 : -1]; /* Dirent.Offset */
typedef char chk_134[(offsetof(struct dirent, d_reclen) == 16) ? 1 : -1]; /* Dirent.Reclen */
typedef char chk_135[(sizeof(((struct dirent *)0)->d_reclen) == 2) ? 1 : -1]; /* Dirent.Reclen */
typedef char chk_136[(offsetof(struct dirent, d_namelen) == 18) ? 1 : -1]; /* Dirent.Namelen */
typedef char chk_137[(sizeof(((struct dirent *)0)->d_namelen) == 2) ? 1 : -1]; /* Dirent.Namelen */
typedef char chk_138[(offsetof(struct dirent, d_name) == 20) ? 1 : -1]; /* Dirent.Name */
typedef char chk_139[(sizeof(((struct dirent *)0)->d_name) == 1) ? 1 : -1]; /* Dirent.Name */
typedef char chk_140[(sizeof(struct sockaddr_in) == 16) ? 1 : -1]; /* RawSockaddrInet4 */
typedef char chk_141[(offsetof(struct sockaddr_in, sin_len) == 0) ? 1 : -1]; /* RawSockaddrInet4.Len */
typedef char chk_142[(sizeof(((struct sockaddr_in *)0)->sin_len) == 1) ? 1 : -1]; /* RawSockaddrInet4.Len */
typedef char chk_143[(offsetof(struct sockaddr_in, sin_family) == 1) ? 1 : -1]; /* RawSockaddrInet4.Family */
typedef char chk_144[(sizeof(((struct sockaddr_in *)0)->sin_family) == 1) ? 1 : -1]; /* RawSockaddrInet4.Family */
typedef char chk_145[(offsetof(struct sockaddr_in, sin_port) == 2) ? 1 : -1]; /* RawSockaddrInet4.Port */
typedef char chk_146[(sizeof(((struct sockaddr_in *)0)->sin_port) == 2) ? 1 : -1]; /* RawSockaddrInet4.Port */
typedef char chk_147[(offsetof(struct sockaddr_in, sin_addr) == 4) ? 1 : -1]; /* RawSockaddrInet4.Addr */
typedef char chk_148[(sizeof(((struct sockaddr_in *)0)->sin_addr) == 4) ? 1 : -1]; /* RawSockaddrInet4.Addr */
typedef char chk_149[(offsetof(struct sockaddr_in, sin_zero) == 8) ? 1 : -1]; /* RawSockaddrInet4.Zero */
typedef char chk_150[(sizeof(((struct sockaddr_in *)0)->sin_zero) == 8) ? 1 : -1]; /* RawSockaddrInet4.Zero */
typedef char chk_151[(sizeof(struct sockaddr_in6) == 28) ? 1 : -1]; /* RawSockaddrInet6 */
typedef char chk_152[(offsetof(struct sockaddr_in6, sin6_len) == 0) ? 1 : -1]; /* RawSockaddrInet6.Len */
typedef char chk_153[(sizeof(((struct sockaddr_in6 *)0)->sin6_len) == 1) ? 1 : -1]; /* RawSockaddrInet6.Len */
typedef char chk_154[(offsetof(struct sockaddr_in6, sin6_family) == 1) ? 1 : -1]; /* RawSockaddrInet6.Family */
typedef char chk_155[(sizeof(((struct sockaddr_in6 *)0)->sin6_family) == 1) ? 1 : -1]; /* RawSockaddrInet6.Family */
typedef char chk_156[(offsetof(struct sockaddr_in6, sin6_port) == 2) ? 1 : -1]; /* RawSockaddrInet6.Port */
typedef char chk_157[(sizeof(((struct sockaddr_in6 *)0)->sin6_port) == 2) ? 1 : -1]; /* RawSockaddrInet6.Port */
typedef char chk_158[(offsetof(struct sockaddr_in6, sin6_flowinfo) == 4) ? 1 : -1]; /* RawSockaddrInet6.Flowinfo */
typedef char chk_159[(sizeof(((struct sockaddr_in6 *)0)->sin6_flowinfo) == 4) ? 1 : -1]; /* RawSockaddrInet6.Flowinfo */
typedef char chk_160[(offsetof(struct sockaddr_in6, sin6_addr) == 8) ? 1 : -1]; /* RawSockaddrInet6.Addr */
typedef char chk_161[(sizeof(((struct sockaddr_in6 *)0)->sin6_addr) == 16) ? 1 : -1]; /* RawSockaddrInet6.Addr */
typedef char chk_162[(offsetof(struct sockaddr_in6, sin6_scope_id) == 24) ? 1 : -1]; /* RawSockaddrInet6.Scope_id */
typedef char chk_163[(sizeof(((struct sockaddr_in6 *)0)->sin6_scope_id) == 4) ? 1 : -1]; /* RawSockaddrInet6.Scope_id */
typedef char chk_164[(sizeof(struct sockaddr_un) == 106) ? 1 : -1]; /* RawSockaddrUnix */
typedef char chk_165[(offsetof(struct sockaddr_un, sun_len) == 0) ? 1 : -1]; /* RawSockaddrUnix.Len */
typedef char chk_166[(sizeof(((struct sockaddr_un *)0)->sun_len) == 1) ? 1 : -1]; /* RawSockaddrUnix.Len */
typedef char chk_167[(offsetof(struct sockaddr_un, sun_family) == 1) ? 1 : -1]; /* RawSockaddrUnix.Family */
typedef char chk_168[(sizeof(((struct sockaddr_un *)0)->sun_family) == 1) ? 1 : -1]; /* RawSockaddrUnix.Family */
typedef char chk_169[(offsetof(struct sockaddr_un, sun_path) == 2) ? 1 : -1]; /* RawSockaddrUnix.Path */
typedef char chk_170[(sizeof(((struct sockaddr_un *)0)->sun_path) == 104) ? 1 : -1]; /* RawSockaddrUnix.Path */
typedef char chk_171[(sizeof(struct sockaddr_dl) == 20) ? 1 : -1]; /* RawSockaddrDatalink */
typedef char chk_172[(offsetof(struct sockaddr_dl, sdl_len) == 0) ? 1 : -1]; /* RawSockaddrDatalink.Len */
typedef char chk_173[(sizeof(((struct sockaddr_dl *)0)->sdl_len) == 1) ? 1 : -1]; /* RawSockaddrDatalink.Len */
typedef char chk_174[(offsetof(struct sockaddr_dl, sdl_family) == 1) ? 1 : -1]; /* RawSockaddrDatalink.Family */
typedef char chk_175[(sizeof(((struct sockaddr_dl *)0)->sdl_family) == 1) ? 1 : -1]; /* RawSockaddrDatalink.Family */
typedef char chk_176[(offsetof(struct sockaddr_dl, sdl_index) == 2) ? 1 : -1]; /* RawSockaddrDatalink.Index */
typedef char chk_177[(sizeof(((struct sockaddr_dl *)0)->sdl_index) == 2) ? 1 : -1]; /* RawSockaddrDatalink.Index */
typedef char chk_178[(offsetof(struct sockaddr_dl, sdl_type) == 4) ? 1 : -1]; /* RawSockaddrDatalink.Type */
typedef char chk_179[(sizeof(((struct sockaddr_dl *)0)->sdl_type) == 1) ? 1 : -1]; /* RawSockaddrDatalink.Type */
typedef char chk_180[(offsetof(struct sockaddr_dl, sdl_nlen) == 5) ? 1 : -1]; /* RawSockaddrDatalink.Nlen */
typedef char chk_181[(sizeof(((struct sockaddr_dl *)0)->sdl_nlen) == 1) ? 1 : -1]; /* RawSockaddrDatalink.Nlen */
typedef char chk_182[(offsetof(struct sockaddr_dl, sdl_alen) == 6) ? 1 : -1]; /* RawSockaddrDatalink.Alen */
typedef char chk_183[(sizeof(((struct sockaddr_dl *)0)->sdl_alen) == 1) ? 1 : -1]; /* RawSockaddrDatalink.Alen */
typedef char chk_184[(offsetof(struct sockaddr_dl, sdl_slen) == 7) ? 1 : -1]; /* RawSockaddrDatalink.Slen */
typedef char chk_185[(sizeof(((struct sockaddr_dl *)0)->sdl_slen) == 1) ? 1 : -1]; /* RawSockaddrDatalink.Slen */
typedef char chk_186[(offsetof(struct sockaddr_dl, sdl_data) == 8) ? 1 : -1]; /* RawSockaddrDatalink.Data */
typedef char chk_187[(sizeof(((struct sockaddr_dl *)0)->sdl_data) == 12) ? 1 : -1]; /* RawSockaddrDatalink.Data */
typedef char chk_188[(sizeof(struct sockaddr) == 16) ? 1 : -1]; /* RawSockaddr */
typedef char chk_189[(offsetof(struct sockaddr, sa_len) == 0) ? 1 : -1]; /* RawSockaddr.Len */
typedef char chk_190[(sizeof(((struct sockaddr *)0)->sa_len) == 1) ? 1 : -1]; /* RawSockaddr.Len */
typedef char chk_191[(offsetof(struct sockaddr, sa_family) == 1) ? 1 : -1]; /* RawSockaddr.Family */
typedef char chk_192[(sizeof(((struct sockaddr *)0)->sa_family) == 1) ? 1 : -1]; /* RawSockaddr.Family */
typedef char chk_193[(offsetof(struct sockaddr, sa_data) == 2) ? 1 : -1]; /* RawSockaddr.Data */
typedef char chk_194[(sizeof(((struct sockaddr *)0)->sa_data) == 14) ? 1 : -1]; /* RawSockaddr.Data */
typedef char chk_195[(sizeof(struct sockaddr_any) == 108) ? 1 : -1]; /* RawSockaddrAny */
typedef char chk_196[(offsetof(struct sockaddr_any, addr) == 0) ? 1 : -1]; /* RawSockaddrAny.Addr */
typedef char chk_197[(sizeof(((struct sockaddr_any *)0)->addr) == 16) ? 1 : -1]; /* RawSockaddrAny.Addr */
typedef char chk_198[(offsetof(struct sockaddr_any, pad) == 16) ? 1 : -1]; /* RawSockaddrAny.Pad */
typedef char chk_199[(sizeof(((struct sockaddr_any *)0)->pad) == 92) ? 1 : -1]; /* RawSockaddrAny.Pad */
typedef char chk_200[(sizeof(socklen_t) == 4) ? 1 : -1]; /* _Socklen */
typedef char chk_201[(sizeof(struct linger) == 8) ? 1 : -1]; /* Linger */
typedef char chk_202[(offsetof(struct linger, l_onoff) == 0) ? 1 : -1]; /* Linger.Onoff */
typedef char chk_203[(sizeof(((struct linger *)0)->l_onoff) == 4) ? 1 : -1]; /* Linger.Onoff */
typedef char chk_204[(offsetof(struct linger, l_linger) == 4) ? 1 : -1]; /* Linger.Linger */
typedef char chk_205[(sizeof(((struct linger *)0)->l_linger) == 4) ? 1 : -1]; /* Linger.Linger */
typedef char chk_206[(sizeof(struct iovec) == 8) ? 1 : -1]; /* Iovec */
typedef char chk_207[(offsetof(struct iovec, iov_base) == 0) ? 1 : -1]; /* Iovec.Base */
typedef char chk_208[(sizeof(((struct iovec *)0)->iov_base) == 4) ? 1 : -1]; /* Iovec.Base */
typedef char chk_209[(offsetof(struct iovec, iov_len) == 4) ? 1 : -1]; /* Iovec.Len */
typedef char chk_210[(sizeof(((struct iovec *)0)->iov_len) == 4) ? 1 : -1]; /* Iovec.Len */
typedef char chk_211[(sizeof(struct ip_mreq) == 8) ? 1 : -1]; /* IPMreq */
typedef char chk_212[(offsetof(struct ip_mreq, imr_multiaddr) == 0) ? 1 : -1]; /* IPMreq.Multiaddr */
typedef char chk_213[(sizeof(((struct ip_mreq *)0)->imr_multiaddr) == 4) ? 1 : -1]; /* IPMreq.Multiaddr */
typedef char chk_214[(offsetof(struct ip_mreq, imr_interface) == 4) ? 1 : -1]; /* IPMreq.Interface */
typedef char chk_215[(sizeof(((struct ip_mreq *)0)->imr_interface) == 4) ? 1 : -1]; /* IPMreq.Interface */
typedef char chk_216[(sizeof(struct ipv6_mreq) == 20) ? 1 : -1]; /* IPv6Mreq */
typedef char chk_217[(offsetof(struct ipv6_mreq, ipv6mr_multiaddr) == 0) ? 1 : -1]; /* IPv6Mreq.Multiaddr */
typedef char chk_218[(sizeof(((struct ipv6_mreq *)0)->ipv6mr_multiaddr) == 16) ? 1 : -1]; /* IPv6Mreq.Multiaddr */
typedef char chk_219[(offsetof(struct ipv6_mreq, ipv6mr_interface) == 16) ? 1 : -1]; /* IPv6Mreq.Interface */
typedef char chk_220[(sizeof(((struct ipv6_mreq *)0)->ipv6mr_interface) == 4) ? 1 : -1]; /* IPv6Mreq.Interface */
typedef char chk_221[(sizeof(struct msghdr) == 28) ? 1 : -1]; /* Msghdr */
typedef char chk_222[(offsetof(struct msghdr, msg_name) == 0) ? 1 : -1]; /* Msghdr.Name */
typedef char chk_223[(sizeof(((struct msghdr *)0)->msg_name) == 4) ? 1 : -1]; /* Msghdr.Name */
typedef char chk_224[(offsetof(struct msghdr, msg_namelen) == 4) ? 1 : -1]; /* Msghdr.Namelen */
typedef char chk_225[(sizeof(((struct msghdr *)0)->msg_namelen) == 4) ? 1 : -1]; /* Msghdr.Namelen */
typedef char chk_226[(offsetof(struct msghdr, msg_iov) == 8) ? 1 : -1]; /* Msghdr.Iov */
typedef char chk_227[(sizeof(((struct msghdr *)0)->msg_iov) == 4) ? 1 : -1]; /* Msghdr.Iov */
typedef char chk_228[(offsetof(struct msghdr, msg_iovlen) == 12) ? 1 : -1]; /* Msghdr.Iovlen */
typedef char chk_229[(sizeof(((struct msghdr *)0)->msg_iovlen) == 4) ? 1 : -1]; /* Msghdr.Iovlen */
typedef char chk_230[(offsetof(struct msghdr, msg_control) == 16) ? 1 : -1]; /* Msghdr.Control */
typedef char chk_231[(sizeof(((struct msghdr *)0)->msg_control) == 4) ? 1 : -1]; /* Msghdr.Control */
typedef char chk_232[(offsetof(struct msghdr, msg_controllen) == 20) ? 1 : -1]; /* Msghdr.Controllen */
typedef char chk_233[(sizeof(((struct msghdr *)0)->msg_controllen) == 4) ? 1 : -1]; /* Msghdr.Controllen */
typedef char chk_234[(offsetof(struct msghdr, msg_flags) == 24) ? 1 : -1]; /* Msghdr.Flags */
typedef char chk_235[(sizeof(((struct msghdr *)0)->msg_flags) == 4) ? 1 : -1]; /* Msghdr.Flags */
typedef char chk_236[(sizeof(struct cmsghdr) == 12) ? 1 : -1]; /* Cmsghdr */
typedef char chk_237[(offsetof(struct cmsghdr, cmsg_len) == 0) ? 1 : -1]; /* Cmsghdr.Len */
typedef char chk_238[(sizeof(((struct cmsghdr *)0)->cmsg_len) == 4) ? 1 : -1]; /* Cmsghdr.Len */
typedef char chk_239[(offsetof(struct cmsghdr, cmsg_level) == 4) ? 1 : -1]; /* Cmsghdr.Level */
typedef char chk_240[(sizeof(((struct cmsghdr *)0)->cmsg_level) == 4) ? 1 : -1]; /* Cmsghdr.Level */
typedef char chk_241[(offsetof(struct cmsghdr, cmsg_type) == 8) ? 1 : -1]; /* Cmsghdr.Type */
typedef char chk_242[(sizeof(((struct cmsghdr *)0)->cmsg_type) == 4) ? 1 : -1]; /* Cmsghdr.Type */
typedef char chk_243[(sizeof(struct in6_pktinfo) == 20) ? 1 : -1]; /* Inet6Pktinfo */
typedef char chk_244[(offsetof(struct in6_pktinfo, ipi6_addr) == 0) ? 1 : -1]; /* Inet6Pktinfo.Addr */
typedef char chk_245[(sizeof(((struct in6_pktinfo *)0)->ipi6_addr) == 16) ? 1 : -1]; /* Inet6Pktinfo.Addr */
typedef char chk_246[(offsetof(struct in6_pktinfo, ipi6_ifindex) == 16) ? 1 : -1]; /* Inet6Pktinfo.Ifindex */
typedef char chk_247[(sizeof(((struct in6_pktinfo *)0)->ipi6_ifindex) == 4) ? 1 : -1]; /* Inet6Pktinfo.Ifindex */
typedef char chk_248[(sizeof(struct ip6_mtuinfo) == 32) ? 1 : -1]; /* IPv6MTUInfo */
typedef char chk_249[(offsetof(struct ip6_mtuinfo, ip6m_addr) == 0) ? 1 : -1]; /* IPv6MTUInfo.Addr */
typedef char chk_250[(sizeof(((struct ip6_mtuinfo *)0)->ip6m_addr) == 28) ? 1 : -1]; /* IPv6MTUInfo.Addr */
typedef char chk_251[(offsetof(struct ip6_mtuinfo, ip6m_mtu) == 28) ? 1 : -1]; /* IPv6MTUInfo.Mtu */
typedef char chk_252[(sizeof(((struct ip6_mtuinfo *)0)->ip6m_mtu) == 4) ? 1 : -1]; /* IPv6MTUInfo.Mtu */
typedef char chk_253[(sizeof(struct icmp6_filter) == 32) ? 1 : -1]; /* ICMPv6Filter */
typedef char chk_254[(offsetof(struct icmp6_filter, icmp6_filt) == 0) ? 1 : -1]; /* ICMPv6Filter.Filt */
typedef char chk_255[(sizeof(((struct icmp6_filter *)0)->icmp6_filt) == 32) ? 1 : -1]; /* ICMPv6Filter.Filt */
typedef char chk_256[(sizeof(fd_set) == 32) ? 1 : -1]; /* FdSet */
typedef char chk_257[(offsetof(fd_set, fds_bits) == 0) ? 1 : -1]; /* FdSet.Bits */
typedef char chk_258[(sizeof(((fd_set *)0)->fds_bits) == 32) ? 1 : -1]; /* FdSet.Bits */
typedef char chk_259[(sizeof(struct if_msghdr) == 144) ? 1 : -1]; /* IfMsghdr */
typedef char chk_260[(offsetof(struct if_msghdr, ifm_msglen) == 0) ? 1 : -1]; /* IfMsghdr.Msglen */
typedef char chk_261[(sizeof(((struct if_msghdr *)0)->ifm_msglen) == 2) ? 1 : -1]; /* IfMsghdr.Msglen */
typedef char chk_262[(offsetof(struct if_msghdr, ifm_version) == 2) ? 1 : -1]; /* IfMsghdr.Version */
typedef char chk_263[(sizeof(((struct if_msghdr *)0)->ifm_version) == 1) ? 1 : -1]; /* IfMsghdr.Version */
typedef char chk_264[(offsetof(struct if_msghdr, ifm_type) == 3) ? 1 : -1]; /* IfMsghdr.Type */
typedef char chk_265[(sizeof(((struct if_msghdr *)0)->ifm_type) == 1) ? 1 : -1]; /* IfMsghdr.Type */
typedef char chk_266[(offsetof(struct if_msghdr, ifm_addrs) == 4) ? 1 : -1]; /* IfMsghdr.Addrs */
typedef char chk_267[(sizeof(((struct if_msghdr *)0)->ifm_addrs) == 4) ? 1 : -1]; /* IfMsghdr.Addrs */
typedef char chk_268[(offsetof(struct if_msghdr, ifm_flags) == 8) ? 1 : -1]; /* IfMsghdr.Flags */
typedef char chk_269[(sizeof(((struct if_msghdr *)0)->ifm_flags) == 4) ? 1 : -1]; /* IfMsghdr.Flags */
typedef char chk_270[(offsetof(struct if_msghdr, ifm_index) == 12) ? 1 : -1]; /* IfMsghdr.Index */
typedef char chk_271[(sizeof(((struct if_msghdr *)0)->ifm_index) == 2) ? 1 : -1]; /* IfMsghdr.Index */
typedef char chk_272[(offsetof(struct if_msghdr, ifm_data) == 16) ? 1 : -1]; /* IfMsghdr.Data */
typedef char chk_273[(sizeof(((struct if_msghdr *)0)->ifm_data) == 128) ? 1 : -1]; /* IfMsghdr.Data */
typedef char chk_274[(sizeof(struct if_data) == 128) ? 1 : -1]; /* IfData */
typedef char chk_275[(offsetof(struct if_data, ifi_type) == 0) ? 1 : -1]; /* IfData.Type */
typedef char chk_276[(sizeof(((struct if_data *)0)->ifi_type) == 1) ? 1 : -1]; /* IfData.Type */
typedef char chk_277[(offsetof(struct if_data, ifi_addrlen) == 1) ? 1 : -1]; /* IfData.Addrlen */
typedef char chk_278[(sizeof(((struct if_data *)0)->ifi_addrlen) == 1) ? 1 : -1]; /* IfData.Addrlen */
typedef char chk_279[(offsetof(struct if_data, ifi_hdrlen) == 2) ? 1 : -1]; /* IfData.Hdrlen */
typedef char chk_280[(sizeof(((struct if_data *)0)->ifi_hdrlen) == 1) ? 1 : -1]; /* IfData.Hdrlen */
typedef char chk_281[(offsetof(struct if_data, ifi_link_state) == 4) ? 1 : -1]; /* IfData.Link_state */
typedef char chk_282[(sizeof(((struct if_data *)0)->ifi_link_state) == 4) ? 1 : -1]; /* IfData.Link_state */
typedef char chk_283[(offsetof(struct if_data, ifi_mtu) == 8) ? 1 : -1]; /* IfData.Mtu */
typedef char chk_284[(sizeof(((struct if_data *)0)->ifi_mtu) == 8) ? 1 : -1]; /* IfData.Mtu */
typedef char chk_285[(offsetof(struct if_data, ifi_metric) == 16) ? 1 : -1]; /* IfData.Metric */
typedef char chk_286[(sizeof(((struct if_data *)0)->ifi_metric) == 8) ? 1 : -1]; /* IfData.Metric */
typedef char chk_287[(offsetof(struct if_data, ifi_baudrate) == 24) ? 1 : -1]; /* IfData.Baudrate */
typedef char chk_288[(sizeof(((struct if_data *)0)->ifi_baudrate) == 8) ? 1 : -1]; /* IfData.Baudrate */
typedef char chk_289[(offsetof(struct if_data, ifi_ipackets) == 32) ? 1 : -1]; /* IfData.Ipackets */
typedef char chk_290[(sizeof(((struct if_data *)0)->ifi_ipackets) == 8) ? 1 : -1]; /* IfData.Ipackets */
typedef char chk_291[(offsetof(struct if_data, ifi_ierrors) == 40) ? 1 : -1]; /* IfData.Ierrors */
typedef char chk_292[(sizeof(((struct if_data *)0)->ifi_ierrors) == 8) ? 1 : -1]; /* IfData.Ierrors */
typedef char chk_293[(offsetof(struct if_data, ifi_opackets) == 48) ? 1 : -1]; /* IfData.Opackets */
typedef char chk_294[(sizeof(((struct if_data *)0)->ifi_opackets) == 8) ? 1 : -1]; /* IfData.Opackets */
typedef char chk_295[(offsetof(struct if_data, ifi_oerrors) == 56) ? 1 : -1]; /* IfData.Oerrors */
typedef char chk_296[(sizeof(((struct if_data *)0)->ifi_oerrors) == 8) ? 1 : -1]; /* IfData.Oerrors */
typedef char chk_297[(offsetof(struct if_data, ifi_collisions) == 64) ? 1 : -1]; /* IfData.Collisions */
typedef char chk_298[(sizeof(((struct if_data *)0)->ifi_collisions) == 8) ? 1 : -1]; /* IfData.Collisions */
typedef char chk_299[(offsetof(struct if_data, ifi_ibytes) == 72) ? 1 : -1]; /* IfData.Ibytes */
typedef char chk_300[(sizeof(((struct if_data *)0)->ifi_ibytes) == 8) ? 1 : -1]; /* IfData.Ibytes */
typedef char chk_301[(offsetof(struct if_data, ifi_obytes) == 80) ? 1 : -1]; /* IfData.Obytes */
typedef char chk_302[(sizeof(((struct if_data *)0)->ifi_obytes) == 8) ? 1 : -1]; /* IfData.Obytes */
typedef char chk_303[(offsetof(struct if_data, ifi_imcasts) == 88) ? 1 : -1]; /* IfData.Imcasts */
typedef char chk_304[(sizeof(((struct if_data *)0)->ifi_imcasts) == 8) ? 1 : -1]; /* IfData.Imcasts */
typedef char chk_305[(offsetof(struct if_data, ifi_omcasts) == 96) ? 1 : -1]; /* IfData.Omcasts */
typedef char chk_306[(sizeof(((struct if_data *)0)->ifi_omcasts) == 8) ? 1 : -1]; /* IfData.Omcasts */
typedef char chk_307[(offsetof(struct if_data, ifi_iqdrops) == 104) ? 1 : -1]; /* IfData.Iqdrops */
typedef char chk_308[(sizeof(((struct if_data *)0)->ifi_iqdrops) == 8) ? 1 : -1]; /* IfData.Iqdrops */
typedef char chk_309[(offsetof(struct if_data, ifi_noproto) == 112) ? 1 : -1]; /* IfData.Noproto */
typedef char chk_310[(sizeof(((struct if_data *)0)->ifi_noproto) == 8) ? 1 : -1]; /* IfData.Noproto */
typedef char chk_311[(offsetof(struct if_data, ifi_lastchange) == 120) ? 1 : -1]; /* IfData.Lastchange */
typedef char chk_312[(sizeof(((struct if_data *)0)->ifi_lastchange) == 8) ? 1 : -1]; /* IfData.Lastchange */
typedef char chk_313[(sizeof(struct ifa_msghdr) == 20) ? 1 : -1]; /* IfaMsghdr */
typedef char chk_314[(offsetof(struct ifa_msghdr, ifam_msglen) == 0) ? 1 : -1]; /* IfaMsghdr.Msglen */
typedef char chk_315[(sizeof(((struct ifa_msghdr *)0)->ifam_msglen) == 2) ? 1 : -1]; /* IfaMsghdr.Msglen */
typedef char chk_316[(offsetof(struct ifa_msghdr, ifam_version) == 2) ? 1 : -1]; /* IfaMsghdr.Version */
typedef char chk_317[(sizeof(((struct ifa_msghdr *)0)->ifam_version) == 1) ? 1 : -1]; /* IfaMsghdr.Version */
typedef char chk_318[(offsetof(struct ifa_msghdr, ifam_type) == 3) ? 1 : -1]; /* IfaMsghdr.Type */
typedef char chk_319[(sizeof(((struct ifa_msghdr *)0)->ifam_type) == 1) ? 1 : -1]; /* IfaMsghdr.Type */
typedef char chk_320[(offsetof(struct ifa_msghdr, ifam_addrs) == 4) ? 1 : -1]; /* IfaMsghdr.Addrs */
typedef char chk_321[(sizeof(((struct ifa_msghdr *)0)->ifam_addrs) == 4) ? 1 : -1]; /* IfaMsghdr.Addrs */
typedef char chk_322[(offsetof(struct ifa_msghdr, ifam_flags) == 8) ? 1 : -1]; /* IfaMsghdr.Flags */
typedef char chk_323[(sizeof(((struct ifa_msghdr *)0)->ifam_flags) == 4) ? 1 : -1]; /* IfaMsghdr.Flags */
typedef char chk_324[(offsetof(struct ifa_msghdr, ifam_index) == 12) ? 1 : -1]; /* IfaMsghdr.Index */
typedef char chk_325[(sizeof(((struct ifa_msghdr *)0)->ifam_index) == 2) ? 1 : -1]; /* IfaMsghdr.Index */
typedef char chk_326[(offsetof(struct ifa_msghdr, ifam_metric) == 16) ? 1 : -1]; /* IfaMsghdr.Metric */
typedef char chk_327[(sizeof(((struct ifa_msghdr *)0)->ifam_metric) == 4) ? 1 : -1]; /* IfaMsghdr.Metric */
typedef char chk_328[(sizeof(struct rt_msghdr) == 76) ? 1 : -1]; /* RtMsghdr */
typedef char chk_329[(offsetof(struct rt_msghdr, rtm_msglen) == 0) ? 1 : -1]; /* RtMsghdr.Msglen */
typedef char chk_330[(sizeof(((struct rt_msghdr *)0)->rtm_msglen) == 2) ? 1 : -1]; /* RtMsghdr.Msglen */
typedef char chk_331[(offsetof(struct rt_msghdr, rtm_version) == 2) ? 1 : -1]; /* RtMsghdr.Version */
typedef char chk_332[(sizeof(((struct rt_msghdr *)0)->rtm_version) == 1) ? 1 : -1]; /* RtMsghdr.Version */
typedef char chk_333[(offsetof(struct rt_msghdr, rtm_type) == 3) ? 1 : -1]; /* RtMsghdr.Type */
typedef char chk_334[(sizeof(((struct rt_msghdr *)0)->rtm_type) == 1) ? 1 : -1]; /* RtMsghdr.Type */
typedef char chk_335[(offsetof(struct rt_msghdr, rtm_index) == 4) ? 1 : -1]; /* RtMsghdr.Index */
typedef char chk_336[(sizeof(((struct rt_msghdr *)0)->rtm_index) == 2) ? 1 : -1]; /* RtMsghdr.Index */
typedef char chk_337[(offsetof(struct rt_msghdr, zero) == 6) ? 1 : -1]; /* RtMsghdr.Zero */
typedef char chk_338[(sizeof(((struct rt_msghdr *)0)->zero) == 2) ? 1 : -1]; /* RtMsghdr.Zero */
typedef char chk_339[(offsetof(struct rt_msghdr, rtm_flags) == 8) ? 1 : -1]; /* RtMsghdr.Flags */
typedef char chk_340[(sizeof(((struct rt_msghdr *)0)->rtm_flags) == 4) ? 1 : -1]; /* RtMsghdr.Flags */
typedef char chk_341[(offsetof(struct rt_msghdr, rtm_addrs) == 12) ? 1 : -1]; /* RtMsghdr.Addrs */
typedef char chk_342[(sizeof(((struct rt_msghdr *)0)->rtm_addrs) == 4) ? 1 : -1]; /* RtMsghdr.Addrs */
typedef char chk_343[(offsetof(struct rt_msghdr, rtm_pid) == 16) ? 1 : -1]; /* RtMsghdr.Pid */
typedef char chk_344[(sizeof(((struct rt_msghdr *)0)->rtm_pid) == 4) ? 1 : -1]; /* RtMsghdr.Pid */
typedef char chk_345[(offsetof(struct rt_msghdr, rtm_seq) == 20) ? 1 : -1]; /* RtMsghdr.Seq */
typedef char chk_346[(sizeof(((struct rt_msghdr *)0)->rtm_seq) == 4) ? 1 : -1]; /* RtMsghdr.Seq */
typedef char chk_347[(offsetof(struct rt_msghdr, rtm_errno) == 24) ? 1 : -1]; /* RtMsghdr.Errno */
typedef char chk_348[(sizeof(((struct rt_msghdr *)0)->rtm_errno) == 4) ? 1 : -1]; /* RtMsghdr.Errno */
typedef char chk_349[(offsetof(struct rt_msghdr, rtm_use) == 28) ? 1 : -1]; /* RtMsghdr.Use */
typedef char chk_350[(sizeof(((struct rt_msghdr *)0)->rtm_use) == 4) ? 1 : -1]; /* RtMsghdr.Use */
typedef char chk_351[(offsetof(struct rt_msghdr, rtm_inits) == 32) ? 1 : -1]; /* RtMsghdr.Inits */
typedef char chk_352[(sizeof(((struct rt_msghdr *)0)->rtm_inits) == 4) ? 1 : -1]; /* RtMsghdr.Inits */
typedef char chk_353[(offsetof(struct rt_msghdr, rtm_rmx) == 36) ? 1 : -1]; /* RtMsghdr.Rmx */
typedef char chk_354[(sizeof(((struct rt_msghdr *)0)->rtm_rmx) == 40) ? 1 : -1]; /* RtMsghdr.Rmx */
typedef char chk_355[(sizeof(struct rt_metrics) == 40) ? 1 : -1]; /* RtMetrics */
typedef char chk_356[(offsetof(struct rt_metrics, rmx_locks) == 0) ? 1 : -1]; /* RtMetrics.Locks */
typedef char chk_357[(sizeof(((struct rt_metrics *)0)->rmx_locks) == 4) ? 1 : -1]; /* RtMetrics.Locks */
typedef char chk_358[(offsetof(struct rt_metrics, rmx_mtu) == 4) ? 1 : -1]; /* RtMetrics.Mtu */
typedef char chk_359[(sizeof(((struct rt_metrics *)0)->rmx_mtu) == 4) ? 1 : -1]; /* RtMetrics.Mtu */
typedef char chk_360[(offsetof(struct rt_metrics, rmx_hopcount) == 8) ? 1 : -1]; /* RtMetrics.Hopcount */
typedef char chk_361[(sizeof(((struct rt_metrics *)0)->rmx_hopcount) == 4) ? 1 : -1]; /* RtMetrics.Hopcount */
typedef char chk_362[(offsetof(struct rt_metrics, rmx_expire) == 12) ? 1 : -1]; /* RtMetrics.Expire */
typedef char chk_363[(sizeof(((struct rt_metrics *)0)->rmx_expire) == 4) ? 1 : -1]; /* RtMetrics.Expire */
typedef char chk_364[(offsetof(struct rt_metrics, rmx_recvpipe) == 16) ? 1 : -1]; /* RtMetrics.Recvpipe */
typedef char chk_365[(sizeof(((struct rt_metrics *)0)->rmx_recvpipe) == 4) ? 1 : -1]; /* RtMetrics.Recvpipe */
typedef char chk_366[(offsetof(struct rt_metrics, rmx_sendpipe) == 20) ? 1 : -1]; /* RtMetrics.Sendpipe */
typedef char chk_367[(sizeof(((struct rt_metrics *)0)->rmx_sendpipe) == 4) ? 1 : -1]; /* RtMetrics.Sendpipe */
typedef char chk_368[(offsetof(struct rt_metrics, rmx_ssthresh) == 24) ? 1 : -1]; /* RtMetrics.Ssthresh */
typedef char chk_369[(sizeof(((struct rt_metrics *)0)->rmx_ssthresh) == 4) ? 1 : -1]; /* RtMetrics.Ssthresh */
typedef char chk_370[(offsetof(struct rt_metrics, rmx_rtt) == 28) ? 1 : -1]; /* RtMetrics.Rtt */
typedef char chk_371[(sizeof(((struct rt_metrics *)0)->rmx_rtt) == 4) ? 1 : -1]; /* RtMetrics.Rtt */
typedef char chk_372[(offsetof(struct rt_metrics, rmx_rttvar) == 32) ? 1 : -1]; /* RtMetrics.Rttvar */
typedef char chk_373[(sizeof(((struct rt_metrics *)0)->rmx_rttvar) == 4) ? 1 : -1]; /* RtMetrics.Rttvar */
typedef char chk_374[(offsetof(struct rt_metrics, rmx_pksent) == 36) ? 1 : -1]; /* RtMetrics.Pksent */
typedef char chk_375[(sizeof(((struct rt_metrics *)0)->rmx_pksent) == 4) ? 1 : -1]; /* RtMetrics.Pksent */
typedef char chk_376[(sizeof(struct utsname) == 1285) ? 1 : -1]; /* Utsname */
typedef char chk_377[(offsetof(struct utsname, sysname) == 0) ? 1 : -1]; /* Utsname.Sysname */
typedef char chk_378[(sizeof(((struct utsname *)0)->sysname) == 257) ? 1 : -1]; /* Utsname.Sysname */
typedef char chk_379[(offsetof(struct utsname, nodename) == 257) ? 1 : -1]; /* Utsname.Nodename */
typedef char chk_380[(sizeof(((struct utsname *)0)->nodename) == 257) ? 1 : -1]; /* Utsname.Nodename */
typedef char chk_381[(offsetof(struct utsname, release) == 514) ? 1 : -1]; /* Utsname.Release */
typedef char chk_382[(sizeof(((struct utsname *)0)->release) == 257) ? 1 : -1]; /* Utsname.Release */
typedef char chk_383[(offsetof(struct utsname, version) == 771) ? 1 : -1]; /* Utsname.Version */
typedef char chk_384[(sizeof(((struct utsname *)0)->version) == 257) ? 1 : -1]; /* Utsname.Version */
typedef char chk_385[(offsetof(struct utsname, machine) == 1028) ? 1 : -1]; /* Utsname.Machine */
typedef char chk_386[(sizeof(((struct utsname *)0)->machine) == 257) ? 1 : -1]; /* Utsname.Machine */
typedef char chk_387[(sizeof(sigset_t) == 8) ? 1 : -1]; /* Sigset_t */
typedef char chk_388[(offsetof(sigset_t, __bits) == 0) ? 1 : -1]; /* Sigset_t.X__bits */
typedef char chk_389[(sizeof(((sigset_t *)0)->__bits) == 8) ? 1 : -1]; /* Sigset_t.X__bits */
typedef char chk_390[(sizeof(stack_t) == 12) ? 1 : -1]; /* Stack_t */
typedef char chk_391[(offsetof(stack_t, ss_sp) == 0) ? 1 : -1]; /* Stack_t.Sp */
typedef char chk_392[(sizeof(((stack_t *)0)->ss_sp) == 4) ? 1 : -1]; /* Stack_t.Sp */
typedef char chk_393[(offsetof(stack_t, ss_size) == 4) ? 1 : -1]; /* Stack_t.Size */
typedef char chk_394[(sizeof(((stack_t *)0)->ss_size) == 4) ? 1 : -1]; /* Stack_t.Size */
typedef char chk_395[(offsetof(stack_t, ss_flags) == 8) ? 1 : -1]; /* Stack_t.Flags */
typedef char chk_396[(sizeof(((stack_t *)0)->ss_flags) == 4) ? 1 : -1]; /* Stack_t.Flags */
typedef char chk_397[(sizeof(struct termios) == 76) ? 1 : -1]; /* Termios */
typedef char chk_398[(offsetof(struct termios, c_iflag) == 0) ? 1 : -1]; /* Termios.Iflag */
typedef char chk_399[(sizeof(((struct termios *)0)->c_iflag) == 4) ? 1 : -1]; /* Termios.Iflag */
typedef char chk_400[(offsetof(struct termios, c_oflag) == 4) ? 1 : -1]; /* Termios.Oflag */
typedef char chk_401[(sizeof(((struct termios *)0)->c_oflag) == 4) ? 1 : -1]; /* Termios.Oflag */
typedef char chk_402[(offsetof(struct termios, c_cflag) == 8) ? 1 : -1]; /* Termios.Cflag */
typedef char chk_403[(sizeof(((struct termios *)0)->c_cflag) == 4) ? 1 : -1]; /* Termios.Cflag */
typedef char chk_404[(offsetof(struct termios, c_lflag) == 12) ? 1 : -1]; /* Termios.Lflag */
typedef char chk_405[(sizeof(((struct termios *)0)->c_lflag) == 4) ? 1 : -1]; /* Termios.Lflag */
typedef char chk_406[(offsetof(struct termios, c_cc) == 16) ? 1 : -1]; /* Termios.Cc */
typedef char chk_407[(sizeof(((struct termios *)0)->c_cc) == 40) ? 1 : -1]; /* Termios.Cc */
typedef char chk_408[(offsetof(struct termios, reserved) == 56) ? 1 : -1]; /* Termios.Reserved */
typedef char chk_409[(sizeof(((struct termios *)0)->reserved) == 12) ? 1 : -1]; /* Termios.Reserved */
typedef char chk_410[(offsetof(struct termios, c_ispeed) == 68) ? 1 : -1]; /* Termios.Ispeed */
typedef char chk_411[(sizeof(((struct termios *)0)->c_ispeed) == 4) ? 1 : -1]; /* Termios.Ispeed */
typedef char chk_412[(offsetof(struct termios, c_ospeed) == 72) ? 1 : -1]; /* Termios.Ospeed */
typedef char chk_413[(sizeof(((struct termios *)0)->c_ospeed) == 4) ? 1 : -1]; /* Termios.Ospeed */
