// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs -- -fsigned-char -D_FILE_OFFSET_BITS=64 -D_QNX_SOURCE types_qnx.go

package syscall

const (
	sizeofPtr      = 0x4
	sizeofShort    = 0x2
	sizeofInt      = 0x4
	sizeofLong     = 0x4
	sizeofLongLong = 0x8
	PathMax        = 0x400
)

type _Sched_param struct {
	Priority    int32
	Curpriority int32
	X__ss_un    [32]byte
}

type _Inheritance struct {
	Flags      uint32
	Pgroup     int32
	Sigmask    Sigset_t
	Sigdefault Sigset_t
	Sigignore  Sigset_t
	Max        uint32
	Policy     int32
	Nd         uint32
	Runmask    uint32
	Param      _Sched_param
}

const (
	_SPAWN_SETGROUP   = 0x1
	_SPAWN_SETSIGMASK = 0x2
	_SPAWN_SETSIGDEF  = 0x4
	_SPAWN_SETSID     = 0x200
	_SPAWN_FDCLOSED   = -0x1
	_SPAWN_NEWPGROUP  = 0x0
)

type (
	_C_short     int16
	_C_int       int32
	_C_long      int32
	_C_long_long int64
)

type Timespec struct {
	Sec  uint32
	Nsec int32
}

type Timeval struct {
	Sec  uint32
	Usec int32
}

type Rusage struct {
	Utime    Timeval
	Stime    Timeval
	Maxrss   int32
	Ixrss    int32
	Idrss    int32
	Isrss    int32
	Minflt   int32
	Majflt   int32
	Nswap    int32
	Inblock  int32
	Oublock  int32
	Msgsnd   int32
	Msgrcv   int32
	Nsignals int32
	Nvcsw    int32
	Nivcsw   int32
}

type Rlimit struct {
	Cur uint64 // C aligns struct rlimit to 8 bytes, Go to 4: never use with sync/atomic
	Max uint64 // C aligns struct rlimit to 8 bytes, Go to 4: never use with sync/atomic
}

type _Pid_t int32

type _Gid_t int32

type Stat_t struct {
	Ino       uint64 // C aligns struct stat to 8 bytes, Go to 4: never use with sync/atomic
	Size      int64  // C aligns struct stat to 8 bytes, Go to 4: never use with sync/atomic
	Dev       uint32
	Rdev      uint32
	Uid       int32
	Gid       int32
	Mtime     uint32
	Atime     uint32
	Ctime     uint32
	Mode      uint32
	Nlink     uint32
	Blocksize uint32
	Nblocks   int32
	Blksize   uint32
	Blocks    uint64 // C aligns struct stat to 8 bytes, Go to 4: never use with sync/atomic
}

type Flock_t struct {
	Type   int16
	Whence int16
	Zero1  int32
	Start  int64 // C aligns struct flock to 8 bytes, Go to 4: never use with sync/atomic
	Len    int64 // C aligns struct flock to 8 bytes, Go to 4: never use with sync/atomic
	Pid    int32
	Sysid  uint32
}

type Dirent struct {
	Ino       uint64 // C aligns struct dirent to 8 bytes, Go to 4: never use with sync/atomic
	Offset    int64  // C aligns struct dirent to 8 bytes, Go to 4: never use with sync/atomic
	Reclen    int16
	Namelen   int16
	Name      [1]int8
	Pad_cgo_0 [3]byte
}

type RawSockaddrInet4 struct {
	Len    uint8
	Family uint8
	Port   uint16
	Addr   [4]byte /* in_addr */
	Zero   [8]int8
}

type RawSockaddrInet6 struct {
	Len      uint8
	Family   uint8
	Port     uint16
	Flowinfo uint32
	Addr     [16]byte /* in6_addr */
	Scope_id uint32
}

type RawSockaddrUnix struct {
	Len    uint8
	Family uint8
	Path   [104]int8
}

type RawSockaddrDatalink struct {
	Len    uint8
	Family uint8
	Index  uint16
	Type   uint8
	Nlen   uint8
	Alen   uint8
	Slen   uint8
	Data   [12]int8
}

type RawSockaddr struct {
	Len    uint8
	Family uint8
	Data   [14]int8
}

type RawSockaddrAny struct {
	Addr RawSockaddr
	Pad  [92]int8
}

type _Socklen uint32

type Linger struct {
	Onoff  int32
	Linger int32
}

type Iovec struct {
	Base *byte
	Len  uint32
}

type IPMreq struct {
	Multiaddr [4]byte /* in_addr */
	Interface [4]byte /* in_addr */
}

type IPv6Mreq struct {
	Multiaddr [16]byte /* in6_addr */
	Interface uint32
}

type Msghdr struct {
	Name       *byte
	Namelen    uint32
	Iov        *Iovec
	Iovlen     int32
	Control    *byte
	Controllen uint32
	Flags      int32
}

type Cmsghdr struct {
	Len   uint32
	Level int32
	Type  int32
}

type Inet6Pktinfo struct {
	Addr    [16]byte /* in6_addr */
	Ifindex uint32
}

type IPv6MTUInfo struct {
	Addr RawSockaddrInet6
	Mtu  uint32
}

type ICMPv6Filter struct {
	Filt [8]uint32
}

const (
	SizeofSockaddrInet4    = 0x10
	SizeofSockaddrInet6    = 0x1c
	SizeofSockaddrAny      = 0x6c
	SizeofSockaddrUnix     = 0x6a
	SizeofSockaddrDatalink = 0x14
	SizeofLinger           = 0x8
	SizeofIPMreq           = 0x8
	SizeofIPv6Mreq         = 0x14
	SizeofMsghdr           = 0x1c
	SizeofCmsghdr          = 0xc
	SizeofInet6Pktinfo     = 0x14
	SizeofIPv6MTUInfo      = 0x20
	SizeofICMPv6Filter     = 0x20
)

type FdSet struct {
	Bits [8]int32
}

const (
	SizeofIfMsghdr  = 0x90
	SizeofIfData    = 0x80
	SizeofIfaMsghdr = 0x14
	SizeofRtMsghdr  = 0x4c
	SizeofRtMetrics = 0x28
)

type IfMsghdr struct {
	Msglen  uint16
	Version uint8
	Type    uint8
	Addrs   int32
	Flags   int32
	Index   uint16
	Data    IfData
}

type IfData struct {
	Type       uint8
	Addrlen    uint8
	Hdrlen     uint8
	Link_state int32
	Mtu        uint64 // C aligns struct if_data to 8 bytes, Go to 4: never use with sync/atomic
	Metric     uint64 // C aligns struct if_data to 8 bytes, Go to 4: never use with sync/atomic
	Baudrate   uint64 // C aligns struct if_data to 8 bytes, Go to 4: never use with sync/atomic
	Ipackets   uint64 // C aligns struct if_data to 8 bytes, Go to 4: never use with sync/atomic
	Ierrors    uint64 // C aligns struct if_data to 8 bytes, Go to 4: never use with sync/atomic
	Opackets   uint64 // C aligns struct if_data to 8 bytes, Go to 4: never use with sync/atomic
	Oerrors    uint64 // C aligns struct if_data to 8 bytes, Go to 4: never use with sync/atomic
	Collisions uint64 // C aligns struct if_data to 8 bytes, Go to 4: never use with sync/atomic
	Ibytes     uint64 // C aligns struct if_data to 8 bytes, Go to 4: never use with sync/atomic
	Obytes     uint64 // C aligns struct if_data to 8 bytes, Go to 4: never use with sync/atomic
	Imcasts    uint64 // C aligns struct if_data to 8 bytes, Go to 4: never use with sync/atomic
	Omcasts    uint64 // C aligns struct if_data to 8 bytes, Go to 4: never use with sync/atomic
	Iqdrops    uint64 // C aligns struct if_data to 8 bytes, Go to 4: never use with sync/atomic
	Noproto    uint64 // C aligns struct if_data to 8 bytes, Go to 4: never use with sync/atomic
	Lastchange Timeval
}

type IfaMsghdr struct {
	Msglen  uint16
	Version uint8
	Type    uint8
	Addrs   int32
	Flags   int32
	Index   uint16
	Metric  int32
}

type RtMsghdr struct {
	Msglen  uint16
	Version uint8
	Type    uint8
	Index   uint16
	Zero    uint16
	Flags   int32
	Addrs   int32
	Pid     int32
	Seq     int32
	Errno   int32
	Use     int32
	Inits   uint32
	Rmx     RtMetrics
}

type RtMetrics struct {
	Locks    uint32
	Mtu      uint32
	Hopcount uint32
	Expire   uint32
	Recvpipe uint32
	Sendpipe uint32
	Ssthresh uint32
	Rtt      uint32
	Rttvar   uint32
	Pksent   uint32
}

type Utsname struct {
	Sysname  [257]int8
	Nodename [257]int8
	Release  [257]int8
	Version  [257]int8
	Machine  [257]int8
}

type Sigset_t struct {
	X__bits [2]int32
}

type Stack_t struct {
	Sp    *byte
	Size  uint32
	Flags int32
}

type Termios struct {
	Iflag    uint32
	Oflag    uint32
	Cflag    uint32
	Lflag    uint32
	Cc       [40]uint8
	Reserved [3]uint32
	Ispeed   int32
	Ospeed   int32
}
